apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-kv
spec:
  containers:
  - name: nginx-flex-kv
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      secretRef:
        name: kvcreds
      options:
        usepodidentity: "false" # OPTIONAL, if not provided, will default to "false"
        keyvaultname: ""
        keyvaultobjectname: ""
        keyvaultobjecttype: secret # OPTIONS: secret, key, cert
        keyvaultobjectversion: "" # OPTIONAL, if not provided, will get latest
        resourcegroup: ""
        subscriptionid: ""
        tenantid: ""
