apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-flex-kv-podid
    aadpodidbinding: "NAME OF the AzureIdentityBinding SELECTOR"
  name: nginx-flex-kv-podid
spec:
  containers:
  - name: nginx-flex-kv-podid
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      options:
        usepodidentity: "true" # OPTIONAL, if not provided, will default to "false"
        keyvaultname: ""
        keyvaultobjectname: ""
        keyvaultobjecttype: secret # OPTIONS: secret, key, cert
        keyvaultobjectversion: "" # OPTIONAL, if not provided, will get latest
        resourcegroup: ""
        subscriptionid: ""
        tenantid: ""
